#Hugo configuration
title = "wqesdf erwk"
baseURL = "https:\/\/were.wer.ertfg"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
